# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.11.x
  - 1.12.x
  - tip

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

stages:
  - test
  - build

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.
before_script:
  - go get gotest.tools/gotestsum

script:
jobs:
  include:
    - stage: test
      script:
        - gotestsum --format short-verbose --raw-command go test -json -race -v -coverprofile=coverage.txt -covermode=atomic -short ./... # -short flag will be removed when parser is done
    - stage: build
      script:
        # TODO: artifacts
        - go build -o gojis ./cmd
