language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - tip
go_import_path: github.com/gojisvm/gojis

env:
  matrix:
  - GO111MODULE=on

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - go test -race ./...
